export const homeObjOne = {
    id: 'liveStreams',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium content',
    headline: 'Live broadcasts for $messi holders',
    description: "Get access to our exclusive Crypto live streams where you can learn from people who have been in Crypto for more than 7 years ",
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/streaming.svg').default,
    alt: "Car",
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'graphic',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Learn about your tokens',
    headline: 'Graphical analysis so you can learn to invest',
    description: "We have you covered no matter where you are located, all you need is an internet connection and a phone or computer",
    buttonLabel: '',
    imgStart: true,
    img: require('../../images/graphicAnalisys.svg').default,
    alt: "Pig",
    dark: true,
    primary: false,
    darkText: true,
}

export const homeObjThree = {
    id: 'predictions',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'We got your back',
    headline: 'Predictions to help you get the best tokens as early as you can',
    description: "Get advice about new tokens that will pump, but don't forget to DO YOUR OWN RESEARCH!",
    buttonLabel: '',
    imgStart: false,
    img: require('../../images/predictions.svg').default,
    alt: "Credit card",
    dark: true,
    primary: false,
    darkText: false,
}